### ISSUE TITLE
Exploratory data analysis example

### ISSUE THREAD

**Issue by edublancas** [ploomber/projects#13]
*Note: working on this requires some familiarity with ploomber* 

People use Ploomber for exploratory data analysis, it'd be great to have an example that helps them get started quickly.

A simple pipeline with three tasks would be enough:

```
load.py -> clean.py -> plot.py
```

Although we would need to choose a [sample dataset](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.datasets), the plot code should be generic and generate charts for each column in the clean data frame depending on the data type (e.g., histograms for real numbers). this could be very useful as a starting point for exploratory projects

**Comment by akash9579** [comment]
Hi @edublancas,
I would like to work on this issue 
can u assign me this issue

**Comment by edublancas** [comment]
Added in 952cf730629c2f164187398cebe0956c96a86702
