### ISSUE TITLE
Plot issues in the first-pipeline colab example

### ISSUE THREAD

**Issue by 94rain** [ploomber/projects#37]
**Related file**: https://github.com/ploomber/projects/blob/master/guides/first-pipeline/colab.ipynb

**Steps to reproduce**:
1. Open https://colab.research.google.com/github/ploomber/projects/blob/master/guides/first-pipeline/colab.ipynb
2. Run the first two blocks. The second block will produce the following error:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/21193371/168908518-d8cbea1c-8c66-44ec-b5aa-0f4bec9ca674.png">

3. Run `ploomber plot` will also produce errors:
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/21193371/168908700-3b515837-af08-400a-b8e4-935e72e0c756.png">

**Potential causes and solutions**:

Colab may have some pre-installed packages (lack of backward compatibility) with higher versions than what is required by Ploomber.

A simple fix can be adding `!pip uninstall -y -r <(pip freeze)` to the top to remove all pre-installed packages first (which will increase the bootstrap time a bit). 

The long-term solution is either to enforce package versions in the `requirements.txt` file of Ploomber or to update the codebase to be compatible with packages of higher versions.

**Comment by edublancas** [comment]
hi! thanks for reporting this. I temporarily removed the link to the colab notebook from the readme as fixing this requires making some changes and uploading a new release.

for more details, see: https://github.com/ploomber/ploomber/issues/786

in the meantime, you can use [binder](https://mybinder.org/v2/gh/ploomber/binder-env/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fploomber%252Fprojects%26urlpath%3Dlab%252Ftree%252Fprojects%252Fguides/first-pipeline%252FREADME.ipynb%26branch%3Dmaster)
