### ISSUE TITLE
updating examples that use `grid` 

### ISSUE THREAD

**Issue by edublancas** [ploomber/projects#49]
*Note* this requires ploomber 0.19.8 to be released

In Ploomber 0.19.8, we introduced placeholders so the grid products and task names can reference the task parameters (via `[[placeholders]]` in the `name` and `product` fields. However, the examples here don't use them. We must update every example that uses `grid` so it uses placeholders. see the docs to [learn more](https://docs.ploomber.io/en/latest/api/spec.html#tasks-grid)

[Here's one](https://github.com/ploomber/projects/blob/master/cookbook/grid/pipeline.yaml). But there are others.

**Comment by e1ha** [comment]
For both task name and products, I was thinking of appending all the placeholder parameters? In the example you linked above, I was thinking something like this: 
`    name: fit-[[model-type]]-[[n_estimators]]-[[criterion]]
    # disabling static_analysis because the notebook does not have
    # a fixed set of parameters (depends on random-forest vs ada-boost)
    static_analysis: disable
    product:
      nb: products/report-[[model-type]]-[[n_estimators]]-[[criterion]].html
      model: products/model-[[model-type]]-[[n_estimators]]-[[criterion]].pickle`
Opinions or does that look alright?

**Comment by idomic** [comment]
@e1ha here's the order I'd do it:
- First I'd map all of the examples that has grid usage.
- Then I'd try one sample and test it locally, see it's working fine with the placeholders.
- The example you wrote above should do, if it doesn't have an env.yaml we can use curly brackets {{SOME_VAL}}

**Comment by e1ha** [comment]
I think I have an idea of how to do it for now but I was wondering if those names would be descriptive enough. Like is just including parameters enough (block1) or would it be better to include both parameters and their parameter names (block 2): 
```
block1: 
name: fit-[[model-type]]-[[n_estimators]]-[[criterion]] 
```
vs.
```
block2: 
name: fit-model-type=[[model-type]]-n_estimators=[[n_estimators]]-criterion=[[criterion]] 
```

**Comment by idomic** [comment]
Got it! I think in that case, block 1 is clearer.
