### ISSUE TITLE
Code copy button is broken

### ISSUE THREAD

**Issue by idomic** [ploomber/projects#51]
For instance [here](https://docs.ploomber.io/en/latest/api/_modules/root/ploomber.DAG.html#ploomber.DAG), when a user clicks on copy code, the message is saying the snippet is copied but the code isn't there when pasting (ctrl+V)

**Comment by edublancas** [comment]
I tested this, and both snippets work. perhaps some browser incompatibility? I tested on firefox

**Comment by idomic** [comment]
Try Chrome? I tried on this snippet with Chrome.

**Comment by edublancas** [comment]
tested with Chrome, it works. Perhaps you have an extension that's blocking it?

**Comment by grnnja** [comment]
I've tested it, and the problem is that you have to click on the actual text to get it to copy. Clicking on "Click to copy" doesn't do anything other than change "Click to copy" to "Copied!". 

I'm thinking of changing the behavior so text is only copied when the user pressed "Click to copy"

**Comment by edublancas** [comment]
Ah, thanks for digging into this.

let's make it work so clicking on any part of the terminal works (the part with the black background, top bar, or "click to copy" label). This is more intuitive than forcing users to click on a specific part of it

**Comment by idomic** [comment]
like both, the button and the code.
