### ISSUE TITLE
templates/mlflow issue

### ISSUE THREAD

**Issue by shaleenb** [ploomber/projects#55]
I am unable to `ploomber build` the `templates/mlflow`. Ploomber seems to be trying to import the variables defined in `env.yaml`.

```
ValueError: Invalid dotted path 'file:/home/jovyan/projects/templates/mlflow/mlruns'. Value must be a dot separated string, with at least two parts: [module_name].[function_name]
```

The same thing happens when I set the value for `mlflow_tracking_uri` directly in `pipeline.yaml` instead of parametrising it.

**Comment by edublancas** [comment]
we fixed this but we haven't released the patch. sorry about that!

you can install from git:

```
pip install git+https://github.com/ploomber/ploomber
```

or downgrade:

```
pip install ploomber==0.19.7
```

**Comment by shaleenb** [comment]
That worked. Thank you.
