### ISSUE TITLE
kubernetes example is a bit out of date

### ISSUE THREAD

**Issue by liguodongIOT** [ploomber/projects#6]
> Hi,
> 
> check out the kubernetes example in the documentation https://soopervisor.readthedocs.io/en/latest/tutorials/kubernetes.html

Hi, I found this document a bit out of date.

for example:

`https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgres.yaml` ,

This url has been changed。The new url is `https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml`。

and when I run this command `soopervisor add training --backend argo-workflows`  ,an error occurs.

> Error: Expected environment.lock.yml or requirements.txt.lock at the root directory. Add one.

because I use pip instead of conda,
How should I generate environment.lock.yml or requirements.txt.lock file without using `ploomber install` ?

_Originally posted by @liguodongIOT in https://github.com/ploomber/projects/issues/5#issuecomment-876081348_

**Comment by edublancas** [comment]
Thanks for reporting the broken link, I'll update it.

Regarding environment.lock.yml (run this after installing all required dependencies):

```
conda env export --no-build --file environment.lock.yml
```

or requirements.txt.lock (run this after installing all required dependencies):

```
pip freeze > requirements.lock.txt
```

More details in the docs: https://soopervisor.readthedocs.io/en/latest/
