### ISSUE TITLE
missing instructions in templates/python-api and templates/ml-advanced

### ISSUE THREAD

**Issue by edublancas** [ploomber/projects#62]
in both, we're missing the setup command:

```
pip install -r requirements.txt
pip install --editable .
```

**Comment by RodolfoFerro** [comment]
For the record, Hacktoberfest asks for maintainers (as part of the protocol to consider a valid PR) to assign the corresponding issues to the person/people working on the issue, so I'm assigning this issue to you @94rain, is it ok?
