### ISSUE TITLE
fix broken links

### ISSUE THREAD

**Issue by edublancas** [ploomber/projects#78]
there are a bunch of broken links in this repository, we need to fix them.

to check, run this in the root folder (the directory with the `pyproject.toml` file:

```sh
pip install pkgmt
pkgmt check-links
```

[documentation here](https://pkgmt.readthedocs.io/en/latest/check-links.html)

Note that this will print the URL along with the error code. I recently added this feature to check links ([pkgmt](https://github.com/ploomber/pkgmt) is a package from us), and there are still some quirks. I actually ran the command already and noticed that some error codes should not necessarily be considered "broken links" so some research is needed here, as the tool might need some adjustments.

The ones that are considered broken are 404 HTTP codes, but others, we can discuss.

**Comment by RodolfoFerro** [comment]
Should we add a scheduled job to this one too?
