### ISSUE TITLE
I am not being able to run my ploomber pipeline

### ISSUE THREAD

**Issue by rajitjijo** [ploomber/projects#92]
I am trying out ploomber for a preprocessing pipeline with images but i am just not being able tor run.

So i am trying a tester project with simple tasks here is the context:

first.py:

# + tags=["parameters"]
# declare a list tasks whose products you want to use as inputs
upstream = None

# +
from random import randint

a = randint(10, 20)

with open("products/first.txt", "w") as f:

    f.write(f"Printing from first: {a}")

environment.yaml file:

tasks:
  # Add tasks here...

  # Example
  - source: scripts/first.py
    product:
      data: products/first.txt

 everytime i run ploomber build i get:

Error: Failed to initialize NotebookRunner task with source 'scripts\\first.py'.
Missing key 'nb' in product: "{'data': File('products\\\\first.txt')}". 'nb' must contain the path to the output notebook.

or i get:

Error: Failed to initialize NotebookRunner task with source 'scripts\\first.py'.
Could not determine format for product 'products\\first.txt'. Pass a valid extension ('.html', '.ipynb', '.md', '.pdf', '.rst', and '.tex') or pass "nbconvert_exporter_name".

If you want to generate multiple products, pass a dictionary to product in your pipeline.yaml:

product:
  # nb must contain the path to the output notebook
  nb: products/output-notebook.ipynb
  # other outputs (optional)
  data: products/some-data.csv
  more-data: products/more-data.csv

What am i doing wrong please help..................................................

**Comment by rajitjijo** [comment]
![Screenshot 2024-05-16 204927](https://github.com/ploomber/projects/assets/102761238/22adc0a1-df3d-4109-80f2-2036f4ee08d4)
Idk the markdown messed up the code structure so heres a snapshot

**Comment by edublancas** [comment]
the error is self-explanatory, your tasks needs a key named `nb` with a path to a file, example: `path/to/output.ipynb`, you can also put `.html` as the extension. example: https://github.com/ploomber/projects/blob/c3d8c2f76489b543b0fafc792370741ae340652b/templates/ml-basic/pipeline.yaml#L17

**Comment by rajitjijo** [comment]
But I don’t have a nb file some of your GitHub examples didn’t have a nb key in the yaml file so is it mandatory that I have a file like that?

**Comment by edublancas** [comment]
it is mandatory for .py and .ipynb tasks. if you tasks are python functions, then it's not needed

https://docs.ploomber.io/en/latest/get-started/first-pipeline.html

**Comment by rajitjijo** [comment]
So you're saying if my task is a whole .py file i have to have a html or ipynb output? if not, ploomber don't work?
